Controllers/BedrifterController.cs
using Microsoft.AspNetCore.Mvc;

namespace Resturant_Booking.Controllers;

public class BedrifterController : Controller

{  
    public IActionResult Index()
    {
       
        return View();
    }
    
    
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    // Get current user
    var applicationUser = await UserManager.GetUserAsync(User);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Resturant Booking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Resturant_Booking.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    
    		<a class="logo" asp-area="" asp-controller="Home" asp-action="Index"><i class="ri-home-heart-fill"></i><span>Restaurant Booking</span></a>
    
	    <ul class="navbar">
		    <li><a asp-area="" asp-controller="Home" asp-action="Index">Hjem</a></li>
		    <li><a href="#">Meny</a></li>
		    <li><a href="#">Om</a></li>
		    <li><a href="#">Kontakt</a></li>
		    <li><a asp-area="" asp-controller="Bedrifter" asp-action="Index">Bedrifter</a></li>
	    </ul>
	    <div class="main">
		     @if (User.IsInRole("Admin"))
		     {
			     <li class="nav-item">
				     <a asp-area="" asp-controller="Admin" asp-action="Index">Admin </a>
			     </li>	
		     }
		   
		    
		       @if (SignInManager.IsSignedIn(User) && applicationUser != null)
		       {
			       var restaurantId = applicationUser.RestaurantId;
			       if (restaurantId != null)
			       {
				       <li>
					       <a asp-area="" asp-controller="Restaurant" asp-action="Index" asp-route-id="@restaurantId">Your restaurant</a>
				       </li>   
			       }
			       
			       <li class="nav-item">
				       <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @applicationUser.Name!</a>
			       </li>
			       <li class="nav-item">
				       <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
					       <button type="submit" class="nav-link btn btn-link text-white">Logout</button>
				       </form>
			       </li>
		       }

		       else
		       {
			       <a asp-area="Identity" asp-page="/Account/Register">Sign up</a>
			       <a asp-area="Identity" asp-page="/Account/Login">log in</a>
			       <a href="#">Book Table</a>
		       }
	    </div>


</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer>
	
	<div class="app__footer section__padding" id="login">
	<div class="app__footer-links">
		<div class="app__footer-links_contact">
			<h1 class="app__footer-headtext">Contact Us</h1>
			<p class="p__opensans">jon lilletuns vei 2b</p>
			<p class="p__opensans">telefon:+47 46598513</p>
			<p class="p__opensans">Epost: Kundeservice@restaurantbooking.no</p>
		</div>

		<div class="app__footer-links_logo">
			<h1>Restaurant Booking</h1>
			<p class="p__opensans">&quot;The best way to find yourself is to lose yourself in the service of others.&quot;</p>
			<div class="app__footer-links_icons">
			</div>
		</div>

		<div class="app__footer-links_work">
			<h1 class="app__footer-headtext">Links</h1>
			<p class="p__opensans">Registrer din Restaurant</p>
			<p class="p__opensans">Om oss</p>
			<p class="p__opensans">FAQ</p>
		</div>
	</div>

	<div class="footer__copyright">
		<p class="p__opensans">2022 Restaurant Booking. All Rights reserved.</p>
	</div>
	
	</div>


</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SearchResultPartial.cshtml
@model IEnumerable<Restaurant>

@{
    ViewBag.Title = "title";
}

@foreach (var restaurant in Model)
{
    <h1>@restaurant.Name</h1>
    <h2>@restaurant.Address</h2>
    <h3>@restaurant.PhoneNumber</h3>
}