Controllers/BookingController.cs
using System.Dynamic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Resturant_Booking.Data;
using Resturant_Booking.Models;
using TwilioTest.Data;

namespace Resturant_Booking.Controllers;

public class BookingController : Controller
{
    private ApplicationDbContext _db;
    private UserManager<ApplicationUser> _um;
    private readonly MessageService _messageService = new MessageService();
    
    public BookingController(ApplicationDbContext db, UserManager<ApplicationUser> um)
    {
        _db = db;
        _um = um;
    }
    
    [Authorize]
    public IActionResult Index(string message = "")
    {
        // Get restaurant id
        var restaurantIdString = Url.ActionContext.RouteData.Values["id"]?.ToString();
        var restaurantId = 0;
        if (restaurantIdString != null)
        {
            restaurantId = Int32.Parse(restaurantIdString);
        }

        // Get restaurant from db
        var restaurant = _db.Restaurants.Find(restaurantId);
        // Get tables from database
        var tables = _db.Tables.Where(i => i.RestaurantId == restaurantId);
        // Get reservations
        var reservations = _db.Reservations.Where(i => i.Table.RestaurantId == restaurantId);

        dynamic myModel = new ExpandoObject();
        myModel.Restaurant = restaurant;
        myModel.Tables = tables;
        myModel.Reservations = reservations;
        //myModel.Message = message;
        
        return View(myModel);
    }

    [Authorize]
    [HttpPost]
    public IActionResult Index(Reservation reservation, int seats, int restaurantId)
    {
        // Find tables
        var tables = _db.Tables
            .Where(i => i.RestaurantId == restaurantId) // Only tables at selected restaurant
            .Where(i => i.Seats >= seats)               // Only tables with enough seats
            .OrderBy(i => i.Seats);                     // Ordered from closest to least close in seats
        
            
        var restaurant = _db.Restaurants.Find(restaurantId);

        // Find first available 
        foreach (var table in tables)
        {
            // Check if table is available
            var reservations = _db.Reservations
                .Where(i => i.TableId == table.TableId)
                .Where(i => i.Time >= reservation.Time || i.Time <= reservation.Time.AddHours(1));

            // If an available table is found
            if (!reservations.Any())
            {
                reservation.Table = table;
                break;
            }
        }

        // If no table was found
        if (reservation.Table == null)
        {
            //ViewBag.Message = "No available tables";
            ViewData["Message"] = "No available tables";
            return RedirectToAction("Index", new { message = "No available tables" });
        }
        
        
        // Add user to reservation
        reservation.User = _um.GetUserAsync(User).Result;

        // Add to database and save changes
        _db.Reservations.Add(reservation);
        _db.SaveChanges();
        
        // Return to view of user reservations if we make that
        //ViewBag.Message = "Table reserved";
        ViewData["Message"] = "Table reserved";
        
        // Sends out a confirmation text message
        if (restaurant != null)
        {
            Console.WriteLine("Message sent");
            _messageService.SendMessage(restaurant, reservation);
        }
            
        
        return RedirectToAction("Index", new { message = "Table reserved" });
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Resturant_Booking.Data;
using Resturant_Booking.Models;

namespace Resturant_Booking.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    
       
    private ApplicationDbContext _db;

    public HomeController(ILogger<HomeController> logger, ApplicationDbContext db)
    {
        _logger = logger;
        _db = db;
    }

    public IActionResult Index()
    {
        return View(_db.Restaurants);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/SearchResultController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Resturant_Booking.Data;
using Resturant_Booking.Models;

namespace Resturant_Booking.Controllers;

public class SearchResultController : Controller
{
    private readonly ApplicationDbContext _db;
    
    public SearchResultController(ApplicationDbContext db)
    {
        _db = db;
    }
    
    [HttpGet]
    // Documentation from Microsoft on search bar
    // https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-7.0
    public async Task<IActionResult> Index(string searchCity)
    {
        // Checks if database does not have any restaurants
        if (_db.Restaurants == null)
        {
            return Problem("There are no restaurants in the database.");
        }

        // Gets restaurants from the database
        var restaurants = from r in _db.Restaurants
            select r;

        //Chekcs if search string is empty
        if (!String.IsNullOrEmpty(searchCity))
        {
            // Finds restaurants which has the searched string as substring
            restaurants = restaurants.Where(res => res.Address.Contains(searchCity));
        }

        return View(await restaurants.ToListAsync());
    }
}

Views/Home/Examplecity.cshtml
@model IEnumerable<Restaurant>

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<style>
div.container {
width: 100%;
min-height: 100vh;
padding: 5%;
background-image: linear-gradient(rgba(0,8,51,0.9), rgba(0,8,51,0.9)), url("images/food.jpg");
background-position: center;
background-size: cover;
display: flex;
align-items: center;
justify-content: center;
}
</style>

<div class="Header">
    <h1>Restaurant booker</h1>
</div>
 @foreach (var restaurant in Model)
    {
        // Example
        <div class="container">
            <h3>@restaurant.Name</h3>
            @restaurant.Address<br/>
            @restaurant.Email<br/>
            @restaurant.PhoneNumber<br/>
            <a asp-area="" asp-controller="Booking" asp-action="Index" asp-route-id="@restaurant.RestaurantId">Book</a>
        </div><br/>
    }

Views/Home/Index.cshtml
@model IEnumerable<Restaurant>
@{
    ViewData["Title"] = "Home Page";
}
<link rel="stylesheet" href="~/css/home.css" asp-append-version="true"/>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

   <style>
       div.container {
          width: 100%;
              min-height: 100vh;
              padding: 5%;
              background-image: linear-gradient(rgba(0,8,51,0.9), rgba(0,8,51,0.9)), url("images/food.jpg");
              background-position: center;
              background-size: cover;
              display: flex;
              align-items: center;
              justify-content: center;
       }
   </style>
<body>
   <div class="Header">
       <h1>Restaurant booker</h1>
   </div>
   <div class="container">
       <div class="search-bar">
           <form asp-controller="SearchResult" asp-action="Index" method="get">
               <input type="text" placeholder="Search for city" name="SearchCity">
               <input type="submit"/>
           </form>
       </div>
   </div>
   <div class="quote">
       <h1>The best restaurantes in nearby</h1>
   </div>
   </body>

Views/Home/example searchpage.cshtml
@model TModel

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<style>
    div.container {
       width: 100%;
           min-height: 100vh;
           padding: 5%;
           background-image: linear-gradient(rgba(0,8,51,0.9), rgba(0,8,51,0.9)), url("images/food.jpg");
           background-position: center;
           background-size: cover;
           display: flex;
           align-items: center;
           justify-content: center;
    }
    div.search-bar
    {
     width: 100%;
     max-width: 500px;
     background-color: rgba(255,255,255,0.2);
     display: flex;
     align-items: center;
     float: left;
     border-radius: 60px;
     padding: 10px 20px;
     backdrop-filter: blur(4px) saturate(180%);
    }
    div.search-bar input
    {
     background: transparent;
        flex: 1;
        border: 0;
        outline: black;
        padding: 24px 20px;
        font-size: 20px;
        color: #cac7ff;
    }
    ::placeholder
    {
     color: #cac7ff;
    }
    div.search-bar img
    {
        width: 25px;
        flaot: right;
        
    }
    div.search-bar img
    {
    border:0; 
    width: 60px;
    height: 60px;
    border-radius: 1%;
    background: #58629b;
    cursor: pointer;
    }
    div.Header
    {
    font-size: 50px;
    color: #fff;
    text-align: center;
    }
    div.quote
    {
        font-size: 50px;
            font-weight: 700;
            color: #fff;
            text-align: center;
            margin-bottom: 20px;
    }
</style>
<head>
    <meta name="viewport" content="width= device-width, initital-scale =1.0">
    <title>Test</title>
    //<link rel="stylesheet" href="style.css">
</head>

<body>
<div class="Header">
    <h1>Restaurant booker</h1>
</div>
<div class="container">
    <div class="search-bar">
        <from action="" method="get">
            <input type="text" placeholder="Search for city" name="q">
            <button type="submit"><img src="images/search1.png"></button>
        </from>
    </div>
</div>
<div class="quote">
    <h1>The best restaurantes in nearby</h1>
</div>
</body>
</html>